Добавляет наставника
htmlacademy-htmlcss/2265125-sedona-36 pull request #1
Opened 2023-01-20 11:59 UTC by kskozarenko

2023-01-20 13:28 UTC, Mielilon requested changes

2023-01-20 13:28 UTC, Mielilon commented on Readme.md
> +* Наставник: `Дарья Магомедова`. (https://htmlacademy.ru/profile/id1443345).
Отлично! Поздравляю с успешно выполненной работой с гитом :)
Предлагаю улучшить подпись наставника и сделать ее полноценной ссылкой. 

Для этого нужно обернуть имя наставника в квадратные скобки, а также убрать точку и пробел после имени. Должна получиться такая система: [Имя] (Ссылка). Сейчас я добавила пробел между именем и ссылкой, чтобы продемонстрировать работу изнутри, в проекте этого делать не нужно. 

Можно обратить внимание на то, как выполнена ссылка на профиль студента.

2023-01-21 09:36 UTC, kskozarenko commented on Readme.md
> +* Наставник: `Дарья Магомедова`. (https://htmlacademy.ru/profile/id1443345).
Принято, изменено! :)

2023-01-21 11:17 UTC, Mielilon approved these changes
Отлично! Задание принято :)

2023-01-21 11:17 UTC, merged