Разметка главной страницы и каталога
htmlacademy-htmlcss/2265125-sedona-36 pull request #2
Opened 2023-01-25 15:50 UTC by kskozarenko

2023-01-25 18:54 UTC, Mielilon requested changes
Отличная, продуманная работа! 

Ты правильно воспользовалась тегами (семантика ликует), хорошо подобрала названия для классов, отдельное спасибо за форматирование документа. 

Я оставила несколько небольших замечаний (нет предела совершенству), буду ждать обновление!

2023-01-25 18:54 UTC, Mielilon commented on catalog.html
> +      <header class="inner-header">
По семантике этот блок не является header, поэтому лучше будет заменить его на div.
Сам элемент у нас является фоном-оберткой, поэтому можем задать ему класс background-catalog

2023-01-25 18:54 UTC, Mielilon commented on catalog.html
> +              <img class="breadcrumbs-icon" src="#" alt="Главная страница сайта городка Седона">
Иконка домика будет добавлена с помощью css, так как она декоративная. Тег с изображением нужно убрать. Вместо него стоит поставить скрытый заголовок со значением кнопки.
Например: 
<img width="363" alt="Снимок экрана 2023-01-25 в 21 43 38" src="https://user-images.githubusercontent.com/65778664/214654460-61e3414b-6ba9-4584-8886-6cd8df18eb4e.png">

2023-01-25 18:54 UTC, Mielilon commented on catalog.html
> +            <a class="breadcrumbs-link">Гостиницы</a>
Мы можем убрать ссылку и оставить только текст "Гостиницы", потому что мы уже находимся на этой странице и нам некуда переходить

2023-01-25 18:54 UTC, Mielilon commented on catalog.html
> +        <h2 class="visually-hidden">Фильтры поиска</h2>
Заголовок сейчас сам по себе. Лучше обернуть его и форму в секцию

2023-01-25 18:54 UTC, Mielilon commented on catalog.html
> +            <button class="button hotel-card-more-button" type="submit">Подробнее</button>
"Подробнее" будет ссылкой на товар. Также нужно поправить и в других товарах

2023-01-25 18:54 UTC, Mielilon commented on catalog.html
> +        <ul class="pagination">
Pagination будет у нас нумерованным списком (ol), так как у нас прослеживается явная зависимость от положения элементов: мы не можем поменять местами 1 и 5 элементы.

2023-01-26 07:23 UTC, kskozarenko commented on catalog.html
> +            <a class="breadcrumbs-link">Гостиницы</a>
А разве не будет правильнее использовать ссылку-заглушку?

2023-01-26 12:12 UTC, merged